name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
          sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub && sudo apt update
          sudo dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
          sudo apt update
          sudo apt install -y cuda-toolkit-10-1 libopencv-dev libopenblas-dev
    - name: Build actual turbo-jpeg
      run: git clone https://github.com/libjpeg-turbo/libjpeg-turbo && cd libjpeg-turbo && mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=/usr && make -j $(nproc) && sudo make install
    - name: Configure cmake
      run: mkdir build && cd build && cmake ../ -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.1 -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.1/bin/nvcc
    - name: Make
      run: cd build && make -j $(nproc)
